### PR TITLE
Repository organization, documentation, structure, configuration, etc.

### PR DESCRIPTION
**Pull request by pdaian**
Branch name is misleading :+1: 

@WaHe please review

### CODE REVIEW

**Comment by reklawnos** [comment]
There are a couple of files that you removed whitespace that was there for PEP-8 compliance that I'll fix really quickly. Also I think the style of the Epydoc strings for variables is very messy. I've seen in a few places this style:

```
class SampleClass(object):
    """Summary of class here.

    Longer class information....
    Longer class information....

    Attributes:
        likes_spam: A boolean indicating if we like SPAM or not.
        eggs: An integer count of the eggs we have laid.
    """

    def __init__(self, likes_spam=False):
        """Inits SampleClass with blah."""
        self.likes_spam = likes_spam
        self.eggs = 0

    def public_method(self):
        """Performs operation blah."""
```

Thoughts?

**Comment by pdaian** [comment]
That's Python docstring. We can do #: after a line instead of """ but it'll increase doc width.

**Comment by reklawnos** [comment]
Just updated my comment. Also it seems like that's the vaguely-recommended style by PEP 257 and 258, if that's the standard we can run with it.

**Comment by pdaian** [comment]
Yeah, I like that style also if that's valid... wasn't in the guide I was looking at (http://epydoc.sourceforge.net/manual-docstring.html)... fix the whitespace, we can merge as is, and have a new issue assigned to me for next iteration to convert?   Just so we can get the docs tagged for iteration 2 today (and I have some other stuff to work on for the next hour unfortunately).

**Pull request merged**
