### PR TITLE
Fixed imports for lots of things

### PR DESCRIPTION
**Pull request by reklawnos**
- Fixed importing for a lot of files
- Got rid of `global_imports.py` files and base `imports.py` file
- Removed pyelliptic from directory and added it as a requirement
- Added a number of other libraries to `requirements.txt`
- Moved unit tests to the `unittests` folder
- Changed a couple of small things to better adhere to PEP-8

### CODE REVIEW

**Comment by reklawnos** [comment]
@akkowal2 I'm certain the TravisCI config will have to be changed—can you advise?

**Comment by akkowal2** [comment]
I think the unit tests for Freenet depend on a GUI install Walker.  @bmdahmen can confirm that though.  They probably need to be excluded from the travis unit tests.

**Comment by bmdahmen** [comment]
They definitely need to be excluded.

**Comment by akkowal2** [comment]
@WaHe I got the travis build to pass...but I don't really know how to merge this easily...

**Pull request merged**
